### ISSUE TITLE
Route export via gpx

### ISSUE THREAD

**Issue by andre0707** [andre0707/WorkoutTransferer#1]
add option to export just the routes in standard `.gpx` format.

Feature request came from **Workout Map**. [See here](https://github.com/andre0707/WorkoutMap/issues/8)

**Comment by jan-eckhoff** [comment]
Thanks, I'd like to test that via TestFlight :-)
Crucial part of the feature is that I can filter by activity type and date range.

**Comment by andre0707** [comment]
I have to add an activity type filter then. That is no problem.
Date filter already exists.
Currently the following activity types are supported: 
- walking
- running
- hiking
- cycling
- swimming
- wheelchairWalkPace
- wheelchairRunPace

is something missing here?

**Comment by jan-eckhoff** [comment]
Looks good to me, thx 😊



Gesendet von unterwegs.

Am 05.01.2024 um 16:17 schrieb Andre ***@***.***>:




﻿

I have to add an activity type filter then. That is no problem.
Date filter already exists.
Currently the following activity types are supported:

walking running hiking cycling swimming wheelchairWalkPace wheelchairRunPace 
is something missing here?
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you commented.Message
 ID: ***@***.***>

**Comment by andre0707** [comment]
Looks like Apple was pretty quick with their review. 
First version is available on TestFlight now: https://testflight.apple.com/join/p7dnsNuI

**Comment by jan-eckhoff** [comment]
Looking good! Unfortunately, the tool that I want to use the GPX files for, [GeoActivityPlayground](https://github.com/martin-ueding/geo-activity-playground), has some issues on my machine, so I can't test the output right now. Will do that as soon as those issues get resolved.

**Comment by andre0707** [comment]
Ok great. I will leave the testing phase open for a bit, before publishing the new version. Let me know if something is not working as expected or if it makes sense to have other additions.

I also appreciate App Store reviews for my apps. That's always helpful :)

**Comment by andre0707** [comment]
@jan-eckhoff were you able to test the export output?
If everything works fine, I would end the beta test and release a new version of the app

**Comment by jan-eckhoff** [comment]
Hi Andre,


unfortunately, my target system still seems to have a bug that prevents me from testing the data, so I can’t give you feedback on the complete workflow. However, the GPX files look sensible. If that’s enough for you to close the beta and release the new
 version, that would be completely fine with me :-)


Best,
Jan


Am 26.01.2024 um 19:09 schrieb Andre ***@***.***>:




@jan-eckhoff
 were you able to test the export output?
If everything works fine, I would end the beta test and release a new version of the app
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you were mentioned.Message
 ID: ***@***.***>

**Comment by andre0707** [comment]
Hi Jan, 

I finished version 1.1.
It looked fine in my tests and when I opened the .gpx files with other apps.

If you happen to run in any problems, create a new ticket or open this one here again. 
I will close it as resolved for now.
